name: Deploy to SmarterASP

on:
  push:
    branches:
      - sprint-4
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore Cinema-Management/Cinema-Management.csproj

      - name: Publish
        run: dotnet publish Cinema-Management/Cinema-Management.csproj -c Release -o publish

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: publish/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/.DS_Store
            **/appsettings.json
            **/appsettings.Development.json
            **/*.pdb
